const sampleData = {
  products: [
    {
      name: 'Queijo Maturado com Limão e Laranja',
      slug: 'maturado-limao-laranja',
      category: 'Queijo Longa Maturação',
      description: 'Queijo maturado com limão e laranja',
      images: ['/images/sample-products/p3-1.jpg'],
      price: 99.95,
      brand: 'Fromageria Tesilli',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Queijo Maturado com Goiabada',
      slug: 'maturado-goiabada',
      category: 'Queijo Longa Maturação',
      description: 'Queijo maturado com goiabada',
      images: ['/images/sample-products/p4-1.jpg'],
      price: 39.95,
      brand: 'Fromageria Tesilli',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Queijo Maturado com Alho Frito',
      slug: 'maturado-alho-frito',
      category: 'Queijo Longa Maturação',
      description: 'Queijo maturado com alho frito',
      images: ['/images/sample-products/p5-1.jpg'],
      price: 79.99,
      brand: 'Fromageria Tesilli',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Queijo Maturado com Alho Negro',
      slug: 'maturado-alho-negro',
      category: 'Queijo Longa Maturação',
      description: 'Queijo maturado com alho negro',
      images: ['/images/sample-products/p6-1.jpg'],
      price: 99.99,
      brand: 'Fromageria Tesilli',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
